import { createRequire } from "module";
const require = createRequire("D:/Qisy/QISYFrontend/QISYFrontend-1/package.json");
const { chromium } = require("playwright");
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8777/index.html");
await page.evaluate(() => localStorage.clear()); await page.reload(); await page.waitForTimeout(400);
await page.click('[data-shop="dator"]');
await page.evaluate(() => { const g = PV.game; g.tutorialStep = 3; g.xp = 60; g.spawnTimer = 0.1; Object.assign(g.stock, { 'rtx-4060': 2, 'i5-13400f': 1, 'pro-b760m-p': 2, 'sn580-1tb': 3, 'hyper-212': 2, '4000d-airflow': 2, 'lpx-16-ddr4': 3, 'cv550': 2 }); });
await page.waitForTimeout(1000);
await page.evaluate(() => { PV.game.spawnTimer = 0; });
await page.waitForTimeout(1500);
await page.evaluate(() => { PV.game.spawnTimer = 0; });
await page.waitForTimeout(7000);
await page.screenshot({ path: "D:/GamesProjects/pixelverkstan/tools/out/f1-floor.png" });
console.log(await page.evaluate(() => PV.game.customers.map((c) => c.name + ':' + c.phase + ':' + c.order.title)));
console.log(errors.join("\n") || "inga fel");
await browser.close();
