// Ny butik: tom → köp startpaket → låda kommer → gå fram och packa upp → kund kommer → ta beställning.
import { createRequire } from "module";
const require = createRequire("D:/Qisy/QISYFrontend/QISYFrontend-1/package.json");
const { chromium } = require("playwright");
const OUT = "D:/GamesProjects/pixelverkstan/tools/out/";
const URL = process.argv[2] || "http://localhost:8777/index.html";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 860 } });
const errors = [];
page.on("pageerror", (e) => errors.push(`[pageerror] ${e.message}\n${e.stack}`));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
const ok = (c, m) => { console.log((c ? 'OK   ' : 'FEL  ') + m); if (!c) errors.push(m); };
await page.goto(URL);
await page.evaluate(() => localStorage.clear()); await page.reload(); await page.waitForTimeout(300);
await page.click('[data-shop="dator"]'); await page.click('[data-year="1991"]');
await page.waitForFunction(() => window.PV?.game, null, { timeout: 30000 }); await page.waitForTimeout(1200);
const g0 = await page.evaluate(() => ({ stock: Object.keys(PV.game.stock).length, money: PV.game.money, guide: PV.game.guide()?.title, players: PV.floor.players.length }));
ok(g0.stock === 0 && g0.guide === 'Butiken är tom!', `tom butik (${JSON.stringify(g0)})`);
await page.screenshot({ path: OUT + "sf0-empty.png" });
await page.click('[data-h="shop"]'); await page.waitForSelector('[data-kit]');
await page.screenshot({ path: OUT + "sf1-kit.png" });
await page.click('[data-kit]'); await page.waitForTimeout(300);
const g1 = await page.evaluate(() => ({ boxes: PV.game.deliveries.length, state: PV.game.deliveries[0]?.state, money: PV.game.money, guide: PV.game.guide()?.title }));
ok(g1.boxes === 1 && g1.state === 'coming' && g1.money < g0.money, `startpaket beställt (${JSON.stringify(g1)})`);
await page.waitForFunction(() => PV.game.deliveries[0]?.state === 'arrived', null, { timeout: 30000 });
await page.waitForTimeout(700);
await page.screenshot({ path: OUT + "sf2-box.png" });
// hovra och klicka på lådan
const bpos = await page.evaluate(() => { const f = PV.floor, [x, y] = f.boxPos(0), r = f.canvas.getBoundingClientRect(); return { x: r.left + f.offX + x * f.scale, y: r.top + f.offY + (y - 10) * f.scale }; });
await page.mouse.move(bpos.x, bpos.y); await page.waitForTimeout(300);
await page.screenshot({ path: OUT + "sf3-boxtip.png" });
await page.mouse.click(bpos.x, bpos.y);
await page.waitForSelector('.box-label', { timeout: 8000 });
const walked = await page.evaluate(() => { const p = PV.floor.localPlayer(); return Math.hypot(p.x - (PV.floor.boxPos(0)[0] - 18), p.y - (PV.floor.boxPos(0)[1] + 2)) < 10; });
ok(walked, 'avataren gick fram till lådan');
await page.screenshot({ path: OUT + "sf4-unpack.png" });
await page.click('button:has-text("Packa upp och ställ ut")'); await page.waitForTimeout(600);
const g2 = await page.evaluate(() => ({ boxes: PV.game.deliveries.length, stock: Object.values(PV.game.stock).reduce((a, b) => a + b, 0), shown: Object.keys(PV.game.shown).reduce((a, id) => a + PV.game.shownFree(id), 0) }));
ok(g2.boxes === 0 && g2.stock > 0 && g2.shown === g2.stock, `uppackat och framme (${JSON.stringify(g2)})`);
// första kunden
await page.waitForFunction(() => PV.game.queue()[0]?.phase === 'queue' && !PV.game.queue()[0].moving, null, { timeout: 40000 });
await page.waitForTimeout(500);
await page.screenshot({ path: OUT + "sf5-customer.png" });
const cpos = await page.evaluate(() => { const f = PV.floor, c = PV.game.queue()[0], r = f.canvas.getBoundingClientRect(); return { x: r.left + f.offX + c.x * f.scale, y: r.top + f.offY + (c.y - 14) * f.scale }; });
await page.mouse.click(cpos.x, cpos.y);
await page.waitForSelector('button:has-text("Ta emot")', { timeout: 8000 });
ok(await page.evaluate(() => { const p = PV.floor.localPlayer(); return p.y < 140 && p.x > 290; }), 'avataren står bakom disken');
await page.screenshot({ path: OUT + "sf6-order.png" });
await page.click('button:has-text("Ta emot")'); await page.waitForTimeout(800);
ok(await page.evaluate(() => PV.build.order && PV.floor.localPlayer().away === 'workshop'), 'bygget öppnades och avataren är i verkstaden');
await page.screenshot({ path: OUT + "sf7-build.png" });
console.log(errors.join('\n') || 'inga fel');
await browser.close();
process.exit(errors.length ? 1 : 0);
